name: Add Release Info to Pyxis

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      commit:
        required: true
        type: string
      host:
        required: true
        type: string
    #      enabled:
    #        required: true
    #        type: boolean
    secrets:
      certificate:
        required: true
      certificatePassword:
        required: true

jobs:
  call-pyxis-endpoint:
    name: Add Release Info
    runs-on: ubuntu-latest
    steps:
      - name: Save Certificate
        env:
          CERTIFICATE: ${{ secrets.certificate }}
        run: |
          echo -n $CERTIFICATE | base64 -di  > certificate.p12

      - name: List File System
        run: |
          ls -a
          md5sum certificate.p12

      - name: Show Working Directory
        run: |
          pwd

      - name: Print ENVS
        id: print-envs
        run: printenv


      - name: Call Pyxis API
        run: |
          curl --cert-type P12 --cert '${{ github.workspace }}/certificate.p12:${{ secrets.certificatePassword }}' \
          -H 'Content-Type: application/json' \
          -d '{"commit":"${{ inputs.commit }}","enabled_for_testing":false,"name":"github.com/redhat-openshift-ecosystem/openshift-preflight","version":"${{ inputs.tag }}"}' \
          -X POST \
          https://${{ inputs.host }}/v1/tools
